name: CI CD Pipeline

on:
 push:
   branches: [main]
 pull:
   branches: [main]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    -name: checkout
    uses: actions/checkout@v2

    -name: setup node environment
    uses: actions/setup-node@v2

    -name: install dependencies
    run: npm install
     
    -name: run tests
    run: npm run test

    -name: build project
    run: npm run build